In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("CleanedHIVdataset.csv")
df

mutationlist = ['Mutation 1',
               'Mutation 2',
               'Mutation 3',
               'Mutation 4',
               'Mutation 5',
               'Mutation 6',
               'Mutation 7']

for i in mutationlist:
    df[i] = df[i].fillna(0)
df

In [ ]:
Unique_Alpha = ['0', 'A', 'C', 'F', 'I', 'L', 'M', 'N', 'Q', 'S', 'T', 'V']
encoding = {}
num = 0
for i in Unique_Alpha:
    encoding[i] = num
    num += 1
print(encoding)

In [ ]:
position = 0
for i in mutationlist:
    alpha = []
    num = []
    for j in df[i]:
        if j == 0:
            num.append(0)
            alpha.append(0)
        else:
            n = int(str(j)[0:-1])
            print(n)
            num.append(n)
            a = str(j)[-1]
            val = encoding[a]
            alpha.append(val)
    col1 = i+' Num'
    col2 = i+' Alpha'
    position += 1
    df.insert(position,col1,num)
    position +=1
    df.insert(position,col2,alpha)
    position +=1


In [ ]:
for i in mutationlist:
    del df[i]

In [ ]:
df

In [ ]:
NFVdata = df.copy()
SQVdata = df.copy()
IDVdata = df.copy()
FPVdata = df.copy()
ATVdata = df.copy()
LPVdata = df.copy()
TPVdata = df.copy()
DRVdata = df.copy()

In [ ]:
drugs = ['NFV','SQV','IDV','FPV','ATV','LPV','TPV','DRV']

for i in drugs:
    if i != 'NFV':
        del NFVdata[i]

for i in drugs:
    if i != 'SQV':
        del SQVdata[i]

for i in drugs:
    if i != 'IDV':
        del IDVdata[i]
        
for i in drugs:
    if i != 'FPV':
        del FPVdata[i]
        
for i in drugs:
    if i != 'ATV':
        del ATVdata[i]
        
for i in drugs:
    if i != 'LPV':
        del LPVdata[i]
        
for i in drugs:
    if i != 'TPV':
        del TPVdata[i]
        
for i in drugs:
    if i != 'DRV':
        del DRVdata[i]

In [2]:
nfvdataset = pd.read_csv("NFVdataset.csv")
nfvdataset

Mutation 1 Num  Mutation 1 Alpha  Mutation 2 Num  Mutation 2 Alpha  \
0              90.0               6.0             0.0               0.0   
1              30.0               7.0             0.0               0.0   
2              46.0               4.0            90.0               6.0   
3              46.0               4.0             0.0               0.0   
4              54.0              11.0            82.0               1.0   
..              ...               ...             ...               ...   
279            32.0               4.0            46.0               5.0   
280            30.0               7.0            46.0               5.0   
281            46.0               5.0            48.0               6.0   
282            32.0               4.0            46.0               4.0   
283            48.0              11.0            50.0              11.0   

     Mutation 3 Num  Mutation 3 Alpha  Mutation 4 Num  Mutation 4 Alpha  \
0               0.0               0.0             0.0               0.0   
1               0.0               0.0             0.0               0.0   
2               0.0               0.0             0.0               0.0   
3               0.0               0.0             0.0               0.0   
4              90.0               6.0             0.0               0.0   
..              ...               ...             ...               ...   
279            47.0              11.0            54.0               6.0   
280            54.0               5.0             0.0               0.0   
281            54.0               6.0            82.0               1.0   
282            47.0              11.0            50.0               5.0   
283            54.0               1.0            82.0              10.0   

     Mutation 5 Num  Mutation 5 Alpha  Mutation 6 Num  Mutation 6 Alpha  \
0               0.0               0.0             0.0               0.0   
1               0.0               0.0             0.0               0.0   
2               0.0               0.0             0.0               0.0   
3               0.0               0.0             0.0               0.0   
4               0.0               0.0             0.0               0.0   
..              ...               ...             ...               ...   
279            90.0               6.0             0.0               0.0   
280             0.0               0.0             0.0               0.0   
281            84.0              11.0             0.0               0.0   
282            82.0              10.0            90.0               6.0   
283             0.0               0.0             0.0               0.0   

     Mutation 7 Num  Mutation 7 Alpha    NFV  
0               0.0               0.0    7.3  
1               0.0               0.0   40.0  
2               0.0               0.0   22.0  
3               0.0               0.0   11.0  
4               0.0               0.0   57.0  
..              ...               ...    ...  
279             0.0               0.0   44.0  
280             0.0               0.0  133.0  
281             0.0               0.0    7.2  
282             0.0               0.0    8.3  
283             0.0               0.0   29.0  

[284 rows x 15 columns]

In [3]:
nfvinputs = nfvdataset.copy()
del nfvinputs['NFV']
nfvinputs

nfvoutputs = nfvdataset[['NFV']].copy()
nfvoutputs

NFV
0      7.3
1     40.0
2     22.0
3     11.0
4     57.0
..     ...
279   44.0
280  133.0
281    7.2
282    8.3
283   29.0

[284 rows x 1 columns]

In [4]:
import torch

In [5]:
nfvinputs = nfvinputs.to_numpy()
nfvinputs

array([[90.,  6.,  0., ...,  0.,  0.,  0.],
       [30.,  7.,  0., ...,  0.,  0.,  0.],
       [46.,  4., 90., ...,  0.,  0.,  0.],
       ...,
       [46.,  5., 48., ...,  0.,  0.,  0.],
       [32.,  4., 46., ...,  6.,  0.,  0.],
       [48., 11., 50., ...,  0.,  0.,  0.]])

In [6]:
nfvoutputs = nfvoutputs.to_numpy()
nfvoutputs

array([[7.30e+00],
       [4.00e+01],
       [2.20e+01],
       [1.10e+01],
       [5.70e+01],
       [9.40e+00],
       [8.20e+00],
       [3.90e+01],
       [1.60e+01],
       [4.80e+01],
       [4.00e+01],
       [1.90e+01],
       [8.60e+01],
       [4.90e+01],
       [2.10e+00],
       [7.70e+00],
       [1.10e+01],
       [1.44e+02],
       [3.40e+01],
       [7.40e+01],
       [3.00e-01],
       [2.50e+00],
       [1.80e+01],
       [6.10e+00],
       [1.80e+01],
       [2.50e+01],
       [6.10e+00],
       [1.30e+01],
       [1.50e+01],
       [2.90e+01],
       [1.10e+02],
       [5.00e+01],
       [6.70e+01],
       [2.37e+02],
       [2.50e+01],
       [8.90e+01],
       [1.38e+02],
       [1.70e+01],
       [2.50e+01],
       [1.11e+02],
       [5.80e+01],
       [2.90e+01],
       [3.40e+01],
       [9.40e+01],
       [3.50e+01],
       [1.54e+02],
       [4.70e+01],
       [3.00e+00],
       [9.20e+00],
       [6.50e+01],
       [4.20e+01],
       [2.50e+00],
       [1.90

In [7]:
inputs = torch.from_numpy(nfvinputs)
targets = torch.from_numpy(nfvoutputs)

In [8]:
print(inputs)
print(targets)

tensor([[90.,  6.,  0.,  ...,  0.,  0.,  0.],
        [30.,  7.,  0.,  ...,  0.,  0.,  0.],
        [46.,  4., 90.,  ...,  0.,  0.,  0.],
        ...,
        [46.,  5., 48.,  ...,  0.,  0.,  0.],
        [32.,  4., 46.,  ...,  6.,  0.,  0.],
        [48., 11., 50.,  ...,  0.,  0.,  0.]], dtype=torch.float64)
tensor([[7.3000e+00],
        [4.0000e+01],
        [2.2000e+01],
        [1.1000e+01],
        [5.7000e+01],
        [9.4000e+00],
        [8.2000e+00],
        [3.9000e+01],
        [1.6000e+01],
        [4.8000e+01],
        [4.0000e+01],
        [1.9000e+01],
        [8.6000e+01],
        [4.9000e+01],
        [2.1000e+00],
        [7.7000e+00],
        [1.1000e+01],
        [1.4400e+02],
        [3.4000e+01],
        [7.4000e+01],
        [3.0000e-01],
        [2.5000e+00],
        [1.8000e+01],
        [6.1000e+00],
        [1.8000e+01],
        [2.5000e+01],
        [6.1000e+00],
        [1.3000e+01],
        [1.5000e+01],
        [2.9000e+01],
        [1.1000e+02],
       

In [9]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs.float(), targets.float())
train_ds[0:3]

(tensor([[90.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [30.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [46.,  4., 90.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 tensor([[ 7.3000],
         [40.0000],
         [22.0000]]))

In [10]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [11]:
import torch.nn as nn

model = nn.Linear(14,1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0800,  0.2373, -0.0073, -0.1073,  0.2277,  0.1781, -0.1093,  0.1666,
          0.0024,  0.1753, -0.2308, -0.1810, -0.0083, -0.0025]],
       requires_grad=True)
Parameter containing:
tensor([-0.1360], requires_grad=True)


In [12]:
preds = model(inputs.float())
preds

tensor([[ -5.9098],
        [ -0.8741],
        [ -4.1655],
        [ -2.8656],
        [ 19.0152],
        [ -2.5496],
        [ -2.6283],
        [ 14.6504],
        [ 14.4131],
        [ 16.9068],
        [  5.8133],
        [ -5.5435],
        [  7.8128],
        [  5.5760],
        [ -6.4565],
        [ -5.0380],
        [  6.0323],
        [ 17.9281],
        [ -3.1443],
        [ -2.1740],
        [ -2.9482],
        [ -4.2436],
        [ -4.4727],
        [ -3.3336],
        [ -1.8444],
        [ -1.6386],
        [ -7.7564],
        [ -4.6580],
        [ -3.9282],
        [ 15.9142],
        [  5.9323],
        [ 16.5043],
        [ -3.5709],
        [  3.7910],
        [  7.5048],
        [  8.0501],
        [-16.2368],
        [  7.3021],
        [  7.0648],
        [ 16.0214],
        [ 16.6499],
        [  7.3027],
        [ 18.8007],
        [  8.3352],
        [  7.0771],
        [  2.3217],
        [  9.7024],
        [ -4.5997],
        [ -4.5680],
        [-14.6457],


In [13]:
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs.float()), targets.float())
print(loss)

tensor(23516.7773, grad_fn=<MseLossBackward0>)


In [14]:
opt = torch.optim.SGD(model.parameters(), lr=1e-10)

In [15]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [16]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 6868.1211
Epoch [20/100], Loss: 13597.8623
Epoch [30/100], Loss: 95046.9688
Epoch [40/100], Loss: 1116.9229
Epoch [50/100], Loss: 949.8812
Epoch [60/100], Loss: 4309.7637
Epoch [70/100], Loss: 991.3038
Epoch [80/100], Loss: 100360.9062
Epoch [90/100], Loss: 90050.0234
Epoch [100/100], Loss: 9329.3525
